### ISSUE TITLE
CentOS compile gmssl unsuccessfully

### ISSUE THREAD

**Issue by zhouyh2018** [guanzhi/GmSSL#777]
**Describe the bug**
compile the gmssl

**Expected behavior**
compile successful

**Screenshots**
In file included from test/buildtest_ecschnorr.c:10:0:
include/openssl/ecschnorr.h:54:0: error: unterminated #ifndef
 #ifndef OPENSSL_NO_ECSCHNORR
 ^
In file included from test/buildtest_ecschnorr.c:10:0:
include/openssl/ecschnorr.h:50:0: error: unterminated #ifndef
 #ifndef HEADER_ECSCHNORR_H
 ^
make[1]: *** [test/buildtest_ecschnorr.o] Error 1

**Environments**
- OS: [CentOS Linux release 7.5.1804 (Core) ]
- Compiler: [gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ]

**Additional context**
try to add $ sudo yum install libtool perl-core zlib-devel
no use

**Comment by xiejianjun417** [comment]
> **Describe the bug**
> compile the gmssl
> 
> **Expected behavior**
> compile successful
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> In file included from test/buildtest_ecschnorr.c:10:0:
> include/openssl/ecschnorr.h:54:0: error: unterminated #ifndef
> #ifndef OPENSSL_NO_ECSCHNORR
> ^
> In file included from test/buildtest_ecschnorr.c:10:0:
> include/openssl/ecschnorr.h:50:0: error: unterminated #ifndef
> #ifndef HEADER_ECSCHNORR_H
> ^
> make[1]: *** [test/buildtest_ecschnorr.o] Error 1
> 
> **Environments**
> 
> * OS: [CentOS Linux release 7.5.1804 (Core) ]
> * Compiler: [gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ]
> 
> **Additional context**
> try to add $ sudo yum install libtool perl-core zlib-devel
> no use

我也遇到相同问题，查看文件include/openssl/ecschnorr.h，即可明白错误原因是有两个#ifndef没有匹配#endif
修正如下，即可编译通过

`/* ====================================================================
 * Copyright (c) 2015 - 2019 The GmSSL Project.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *
 * 3. All advertising materials mentioning features or use of this
 *    software must display the following acknowledgment:
 *    "This product includes software developed by the GmSSL Project.
 *    (http://gmssl.org/)"
 *
 * 4. The name "GmSSL Project" must not be used to endorse or promote
 *    products derived from this software without prior written
 *    permission. For written permission, please contact
 *    guanzhi1980@gmail.com.
 *
 * 5. Products derived from this software may not be called "GmSSL"
 *    nor may "GmSSL" appear in their names without prior written
 *    permission of the GmSSL Project.
 *
 * 6. Redistributions of any form whatsoever must retain the following
 *    acknowledgment:
 *    "This product includes software developed by the GmSSL Project
 *    (http://gmssl.org/)"
 *
 * THIS SOFTWARE IS PROVIDED BY THE GmSSL PROJECT ``AS IS'' AND ANY
 * EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE GmSSL PROJECT OR
 * ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 * ====================================================================
 */

#ifndef HEADER_ECSCHNORR_H
#define HEADER_ECSCHNORR_H

#include <openssl/opensslconf.h>
#ifndef OPENSSL_NO_ECSCHNORR

#include <openssl/ec.h>
#include <openssl/err.h>
#include <openssl/evp.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct ECSCHNORR_SIG_st ECSCHNORR_SIG;
DECLARE_ASN1_FUNCTIONS(ECSCHNORR_SIG)

/* return the maximum ec schnorr signature size */
int ECSCHNORR_size(const EC_KEY *ec_key);

ECSCHNORR_SIG *ECSCHNORR_do_sign(const EVP_MD *md,
	const unsigned char *dgst, int dgst_len, EC_KEY *ec_key);
int ECSCHNORR_do_verify(const EVP_MD *md,
	const unsigned char *dgst, int dgstlen,
	const ECSCHNORR_SIG *sig, EC_KEY *ec_key);

int ECSCHNORR_sign(int type, const unsigned char *dgst, int dgstlen,
	unsigned char *sig, unsigned int *siglen, EC_KEY *eckey);
int ECSCHNORR_verify(int type, const unsigned char *dgst, int dgstlen,
	const unsigned char *sig, int siglen, EC_KEY *ec_key);


/* BEGIN ERROR CODES */
#ifdef __cplusplus
}
#endif
#endif//OPENSSL_NO_ECSCHNORR

#endif//HEADER_ECSCHNORR_H
`

**Comment by xiejianjun417** [comment]
@zhouyh2018 @guanzhi

**Comment by zhouyh2018** [comment]
make成功，谢谢

**Comment by tianlitao** [comment]
@xiejianjun417 成功了，谢谢
